version: '3.9'
services:
  redis:
    image: redis:7
    container_name: video-app-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11562773-ecr-repository:latesta2
    container_name: video-app-api
    depends_on:
      - redis
    environment:
      PORT: 3000
      UPLOAD_DIR: /app/uploads
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
volumes:
  pgdata:
  uploads: