version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: video-app-postgres
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: secret_to_your_heart
      POSTGRES_DB: video_app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready -U superman"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: video-app-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  api: 
    image: video-app-api
    build: .
    container_name: video-app-api
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3000
      UPLOAD_DIR: /app/uploads
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
volumes:
  pgdata:
  uploads: