name: Terraform Deploy

on:
  push:
    branches: [ test/tf-backend ]

jobs:
  terraform-deploy:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ap-southeast-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: ./deployment/qut-aws-tfstate-demo
      run: |
        terraform init \
          -backend-config="bucket=cab432-n11562773-tfsate-storage-demo" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=ap-southeast-2" \
          -backend-config="dynamodb_table=n11562773-tfstate-backend-demo"

    - name: Terraform Plan
      working-directory: ./deployment/qut-aws-tfstate-demo
      run: terraform plan -var-file=variables-1.tfvars

    - name: Terraform Apply
      working-directory: ./deployment/qut-aws-tfstate-demo
      run: terraform apply -auto-approve -var-file=variables-1.tfvars